### ISSUE TITLE
When can we expect deflate64?

### ISSUE THREAD

**Issue by focusgizmo** [Pr0methean/zip-next#14]
Hi,

Could you provide information on when or if you plan to include deflate64 in the compression methods?

Thanks

**Comment by Pr0methean** [comment]
Reopening this issue, because the fix can't be released until https://github.com/anatawa12/deflate64-rs/issues/25 is fixed.

**Comment by Pr0methean** [comment]
Update: the deflate64 bug is now fixed, and the new version should be released within the next few days (even if it has to be built against the upstream trunk rather than waiting for the next release).

**Comment by Pr0methean** [comment]
Fix released in 0.11.0.
