### ISSUE TITLE
shallow_copy_file vs symlink compatibility

### ISSUE THREAD

**Issue by enkore** [Pr0methean/zip-next#21]
Tested this a bit:

Reading a shallow_copy_file:

- zip.rs: ok
- Python zipfile: BadZipFile exception (local vs. central directory name mismatch)
- 7z: ok
- unzip -p: ok
- unzip: triggers zip bomb detection

Reading a symlinked file:

- zip.rs: nope (reads link target instead) [1]
- Python zipfile: nope (reads link target instead) [2]
- Python zipfile cli: extracts as text file with link target
- 7z: fails
- unzip -p: reads link target instead
- unzip: restores as symlink

[1] You can tell  it's a symlink via unix_mode().  
[2] You can tell it's a symlink via ZipFile.getinfo and looking at the upper 16 bits of external_attr; that's how repr(ZipInfo) does it.

**Comment by Pr0methean** [comment]
It's expected for `shallow_copy_file` to produce a less widely-accepted ZIP file than `deep_copy_file`; this is documented. As for symlinks, there doesn't seem to be any standard in the case where the symlink target isn't in the same ZIP file.
